version: '3'

services:

  frontend:
    image: ghcr.io/lerkasan/boanerges/boanerges-frontend:${FRONTEND_TAG:-latest} # commit sha from environment variable    aws deploy get-deployment --deployment-id $DEPLOYMENT_ID  --query  ".deploymentInfo.revision.gitHubLocation.commitId" --output text
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    environment:
      - APP_NAME=boanerges
      - NGINX_HOST=lerkasan.net
      - PRIVATE_IP
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
    networks:
      app:
#    logging:
#      driver: awslogs
#      options:
#        awslogs-region: us-east-1
#        awslogs-group: /var/log/nginx
#        awslogs-stream: frontend
    depends_on:
      - backend

  backend:
    image: ghcr.io/lerkasan/boanerges/boanerges-backend:${BACKEND_TAG:-latest} # commit sha from environment variable   aws deploy get-deployment --deployment-id $DEPLOYMENT_ID  --query  ".deploymentInfo.revision.gitHubLocation.commitId" --output text
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    environment:
      - DB_HOST
      - DB_PORT=3306
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - SPRING_SERVER_PORT=8080
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STS_ROLE_ARN
      - DEEPGRAM_API_KEY
      - DEEPGRAM_PROJECT_ID
      - OPENAI_API_KEY
      - SMTP_USERNAME
      - SMTP_PASSWORD
#    volumes:
#      - ./spring-boot/logs:/var/log/spring-boot/
    networks:
      app:
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: boanerges_/var/log/spring-boot
#        awslogs-stream: "{instance_id}_{hostname}"
#        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        tag: '{{ with split .ImageName ":" }}{{join . "_"}}{{end}}/{{.Name}}/{{.ID}}'

networks:
  app:
