version: '3'

services:

  frontend:
    build:
      dockerfile:
        Dockerfile.frontend
      args:
        - APP_NAME=boanerges
#        - NODE_ENV=development
        - VUE_APP_BACKEND_HOST=localhost
        - VUE_APP_BACKEND_PROTOCOL=http
        - VUE_APP_AWS_REGION=${AWS_REGION:-us-east-1}
    container_name: frontend
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    environment:
      - APP_NAME=boanerges
      - NGINX_HOST
      - PRIVATE_IP=127.0.0.1
#      - ENVIRONMENT=development
#      - NODE_ENV=development
#      - VUE_APP_BACKEND_HOST=localhost:9090
#      - VUE_APP_BACKEND_PROTOCOL=http
#      - VUE_APP_AWS_REGION=${AWS_REGION:-us-east-1}
#      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    volumes:
#      - ./infra/nginx_config/:/etc/nginx/templates/
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "80:80"
    networks:
      - app
    depends_on:
      - backend

  backend:
    build:
      dockerfile:
        Dockerfile.backend
    container_name: backend
    restart: always
    read_only: true
    tmpfs:
      - /tmp
#      - /var/lib/tomcat
#      - /var/log/spring-boot
    cap_drop:
      - ALL
    environment:
      - FRONTEND_URL=http://localhost
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - SPRING_SERVER_PORT=${SPRING_SERVER_PORT:-8080}
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STS_ROLE_ARN
      - DEEPGRAM_API_KEY
      - DEEPGRAM_PROJECT_ID
      - OPENAI_API_KEY
      - SMTP_USERNAME
      - SMTP_PASSWORD
#    volumes:
#      - ./tomcat/logs:/var/lib/tomcat/logs
#      - ./spring-boot/logs:/var/log/spring-boot/
#      - ./tomcat:/app/tomcat/
#    command: sh -c "chown javauser:javauser /app/tomcat"
#    ports:
#      - "${SPRING_SERVER_PORT}:${SPRING_SERVER_PORT}"
    networks:
      - app
    depends_on:
      - database

  database:
    hostname: ${DB_HOST:-database}
    image: mysql:8.0.33-debian@sha256:8dd2269034dd8680a2d90403977c9604bbaeb0e30364d105340a50241245785c
    container_name: database
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/mysqld
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - NET_RAW
      - SETGID
      - SETUID
      - SYS_TIME
      - SYSLOG
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_TCP_PORT: ${DB_PORT:-3306}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app

networks:
  app: