FROM node:18.16-alpine@sha256:bf6c61feabc1a1bd565065016abe77fa378500ec75efa67f5b04e5e5c4d447cd AS builder

ARG ENVIRONMENT=production

RUN mkdir /app

WORKDIR /app

COPY frontend .

RUN npm ci && \
    npm run build



FROM nginx:1.24.0-alpine-slim@sha256:da86ecb516d88a5b0579cec8687a75f974712cb5091560c06ef6c393ea4936ee

ARG APP_NAME=boanerges
# ARG DOMAIN_NAME=lerkasan.net
# ENV DOMAIN_NAME=$DOMAIN_NAME

COPY --from=builder /app/dist /var/www/$APP_NAME
COPY infra/nginx_config/default.conf.template /etc/nginx/templates/default.conf.template
#COPY infra/nginx_config/nginx-default.conf /etc/nginx/conf.d/default.conf

# Using ARG during build-time
# RUN sed -i "s/%DOMAIN_NAME%/${DOMAIN_NAME}/g" /etc/nginx/conf.d/default.conf
# RUN apk add nginx-mod-http-headers-more && \
#    sed -i "s/%DOMAIN_NAME%/${DOMAIN_NAME}/g" /etc/nginx/conf.d/default.conf

# Using ENV variable during runtime
#COPY infra/nginx_config/insert_domain_name_in_config.sh /docker-entrypoint.d/insert_domain_name_in_config.sh

#RUN chown nginx:nginx /docker-entrypoint.d/insert_domain_name_in_config.sh && \
#    chmod +x /docker-entrypoint.d/insert_domain_name_in_config.sh

RUN apk add curl

EXPOSE 80
