INSERT INTO categories (name) VALUES ('Software Development');
INSERT INTO categories (name) VALUES ('Databases');
INSERT INTO categories (name) VALUES ('Java');

INSERT INTO topics (name, category_id) VALUES ('Building scalable and fault-tolerant distributed systems', 1);
INSERT INTO topics (name, category_id) VALUES ('Designing RESTful APIs and implementing API versioning strategies', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing event-driven architectures using message brokers', 1);
INSERT INTO topics (name, category_id) VALUES ('Developing real-time streaming applications with Apache Kafka', 3);
INSERT INTO topics (name, category_id) VALUES ('Building reactive applications using reactive programming frameworks', 1);
INSERT INTO topics (name, category_id) VALUES ('Building serverless applications using Java and cloud platforms', 3);
INSERT INTO topics (name, category_id) VALUES ('Implementing search functionality using Elasticsearch or Solr', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing data access and storage with NoSQL databases', 1);
INSERT INTO topics (name, category_id) VALUES ('Securing web applications against common vulnerabilities and attacks', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing authorization and authentication mechanisms', 1);
INSERT INTO topics (name, category_id) VALUES ('Optimizing database queries and improving query performance', 2);
INSERT INTO topics (name, category_id) VALUES ('Implementing data synchronization and replication strategies', 2);

INSERT INTO topics (name, category_id) VALUES ('Designing fault-tolerant and scalable distributed systems', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing microservices architecture and communication patterns', 1);
INSERT INTO topics (name, category_id) VALUES ('Building event-driven systems using message brokers and pub/sub patterns', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing real-time streaming and processing with Apache Kafka or Apache Flink', 1);
INSERT INTO topics (name, category_id) VALUES ('Applying machine learning algorithms and frameworks for data analysis', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing containerization and orchestration using Docker and Kubernetes', 1);
INSERT INTO topics (name, category_id) VALUES ('Designing and optimizing relational databases for performance', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing search functionality with Elasticsearch or Solr', 1);
INSERT INTO topics (name, category_id) VALUES ('Building reactive and asynchronous applications using frameworks like ReactiveX', 1);
INSERT INTO topics (name, category_id) VALUES ('Applying functional programming concepts and patterns in software development', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing secure authentication and authorization mechanisms', 1);
INSERT INTO topics (name, category_id) VALUES ('Designing and optimizing RESTful APIs for performance and scalability', 1);
INSERT INTO topics (name, category_id) VALUES ('Applying DevOps practices for continuous integration and delivery', 1);
INSERT INTO topics (name, category_id) VALUES ('Implementing caching strategies for improved application performance', 1);
INSERT INTO topics (name, category_id) VALUES ('Designing and implementing high-availability systems with load balancing and failover mechanisms', 1);

INSERT INTO topics (name, category_id) VALUES ('Data encryption and security in Java applications', 3);
INSERT INTO topics (name, category_id) VALUES ('Asynchronous programming in Java using CompletableFuture and reactive frameworks', 3);
INSERT INTO topics (name, category_id) VALUES ('Concurrency and multi-threading in Java: synchronization, locks, and concurrent data structures', 3);
INSERT INTO topics (name, category_id) VALUES ('Java memory management: garbage collection algorithms and tuning', 3);
INSERT INTO topics (name, category_id) VALUES ('Design patterns in Java: Singleton, Observer, Factory, Strategy, etc.', 3);
INSERT INTO topics (name, category_id) VALUES ('Java performance optimization techniques: profiling, benchmarking, and code optimization', 3);
INSERT INTO topics (name, category_id) VALUES ('Java networking: TCP/IP, sockets, HTTP, and RESTful API design', 3);
INSERT INTO topics (name, category_id) VALUES ('Java 9+ modules: modularization and encapsulation of code', 3);
INSERT INTO topics (name, category_id) VALUES ('Java I/O and file handling: streams, readers/writers, serialization, and deserialization', 3);
INSERT INTO topics (name, category_id) VALUES ('Java testing frameworks: JUnit, Mockito, and TestNG', 3);
INSERT INTO topics (name, category_id) VALUES ('Java servlets and JavaServer Pages (JSP): web application development with Java EE', 3);
INSERT INTO topics (name, category_id) VALUES ('Java security: authentication, authorization, and secure coding practices', 3);
INSERT INTO topics (name, category_id) VALUES ('Java functional programming: lambda expressions, streams, and functional interfaces', 3);
INSERT INTO topics (name, category_id) VALUES ('Java message queuing systems: JMS, Apache Kafka, and RabbitMQ', 3);
INSERT INTO topics (name, category_id) VALUES ('Java microservices: containerization, service discovery, and communication between microservices', 3);

INSERT INTO topics (name, category_id) VALUES ('Design patterns: Singleton, Observer, Factory, Strategy, etc.', 1);
INSERT INTO topics (name, category_id) VALUES ('Memory management: garbage collection algorithms and tuning', 1);
INSERT INTO topics (name, category_id) VALUES ('Concurrency and multi-threading: synchronization, locks, and concurrent data structures', 1);
INSERT INTO topics (name, category_id) VALUES ('Performance optimization techniques: profiling, benchmarking, and code optimization', 1);
INSERT INTO topics (name, category_id) VALUES ('Networking: TCP/IP, sockets, HTTP, and RESTful API design', 1);
INSERT INTO topics (name, category_id) VALUES ('I/O and file handling: streams, readers/writers, serialization, and deserialization', 3);
INSERT INTO topics (name, category_id) VALUES ('Testing frameworks: JUnit, Mockito, and TestNG', 3);
INSERT INTO topics (name, category_id) VALUES ('Servlets and JavaServer Pages (JSP): web application development with Java EE', 3);
INSERT INTO topics (name, category_id) VALUES ('Security: authentication, authorization, and secure coding practices', 1);
INSERT INTO topics (name, category_id) VALUES ('Functional programming: lambda expressions, streams, and functional interfaces', 3);
INSERT INTO topics (name, category_id) VALUES ('Message queuing systems: JMS, Apache Kafka, and RabbitMQ', 3);
INSERT INTO topics (name, category_id) VALUES ('Microservices: containerization, service discovery, and communication between microservices', 1);
INSERT INTO topics (name, category_id) VALUES ('Data structures and algorithms: arrays, linked lists, stacks, queues, sorting, and searching', 1);
INSERT INTO topics (name, category_id) VALUES ('XML processing: DOM, SAX, XPath, and XSLT', 3);
INSERT INTO topics (name, category_id) VALUES ('Internationalization and localization: handling multilingual applications', 3);
INSERT INTO topics (name, category_id) VALUES ('Reflection and annotation processing: introspection and dynamic code generation', 3);

INSERT INTO topics (name, category_id) VALUES ('Database design principles: normalization, indexing, and query optimization', 2);
INSERT INTO topics (name, category_id) VALUES ('Object-Relational Mapping (ORM) frameworks: Hibernate, JPA, and MyBatis', 3);
INSERT INTO topics (name, category_id) VALUES ('Web frameworks: Spring MVC, JavaServer Faces (JSF), and Play Framework', 3);
INSERT INTO topics (name, category_id) VALUES ('Dependency injection and inversion of control (IoC) containers: Spring, CDI, and Guice', 3);
INSERT INTO topics (name, category_id) VALUES ('RESTful web services: design principles, implementation, and documentation', 1);
INSERT INTO topics (name, category_id) VALUES ('Authentication and authorization frameworks: Spring Security, Apache Shiro, and OAuth', 3);
INSERT INTO topics (name, category_id) VALUES ('Data caching techniques: in-memory caching, Redis, and Memcached', 1);
INSERT INTO topics (name, category_id) VALUES ('Asynchronous programming: CompletableFuture, Reactive Streams, and event-driven architectures', 3);
INSERT INTO topics (name, category_id) VALUES ('Message-driven architectures: JMS, AMQP, and Apache ActiveMQ', 3);
INSERT INTO topics (name, category_id) VALUES ('Big data processing: Apache Hadoop, Apache Spark, and Apache Flink', 1);
INSERT INTO topics (name, category_id) VALUES ('Containerization and orchestration: Docker, Kubernetes, and containerization best practices', 1);
INSERT INTO topics (name, category_id) VALUES ('Continuous integration and delivery (CI/CD) pipelines: Jenkins, GitLab CI/CD, and Travis CI', 1);
INSERT INTO topics (name, category_id) VALUES ('Performance monitoring and profiling tools: JProfiler, VisualVM, and Java Flight Recorder', 3);
INSERT INTO topics (name, category_id) VALUES ('Secure coding practices and common vulnerabilities: OWASP Top 10, input validation, and output encoding', 1);
INSERT INTO topics (name, category_id) VALUES ('Designing scalable and fault-tolerant architectures: load balancing, clustering, and high availability', 1);
