name: Deploy frontend and backend

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'infra/**'
      - 'compose.yml'
      - 'appspec.yml'

# for debugging purposes
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy to AWS
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    secrets: inherit