name: Deploy frontend and backend after IaC changes

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'infra/aws/**'
      - 'infra/terraform/**'
      - 'compose.yml'
      - 'appspec.yml'

# for debugging purposes
  workflow_dispatch:

jobs:

  infrastructure:
    name: Provision AWS infrastructure
    if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      id-token: write  # GitHub OIDC Token
    uses: ./.github/workflows/provision-infrastructure.yml
    secrets: inherit


  deploy:
    name: Deploy to AWS
    needs: [ infrastructure ]
    if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
#    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      contents: read
      id-token: write  # GitHub OIDC Token
    uses: ./.github/workflows/deploy.yml
    secrets: inherit